export const souceData = [
  {
    id: 1,
    title: "Соус Брусничний",
    price: 24,
    weight: "40 грам",
    picture: "brus.webp",
  },
  {
    id: 2,
    title: "Соус Тартар",
    price: 24,
    weight: "40 грам",
    picture: "tar.webp",
  },
  {
    id: 3,
    title: "Соус Часниковий",
    price: 19,
    weight: "40 грам",
    picture: "chasnykovyi.webp",
  },
  {
    id: 4,
    title: "Соус Сирний",
    price: 25,
    weight: "40 грам",
    picture: "syr.webp",
  },
  {
    id: 5,
    title: "Соус Кетчуп",
    price: 19,
    weight: "40 грам",
    picture: "ketchup.webp",
  },
  {
    id: 6,
    title: "Соус Солодкий Чилі",
    price: 25,
    weight: "40 грам",
    picture: "solodkyj-chyli.webp",
  },
  {
    id: 7,
    title: "Соус Барбекю",
    price: 24,
    weight: "40 грам",
    picture: "bbq.webp",
  },
  {
    id: 8,
    title: "Соус Цезар",
    price: 25,
    weight: "40 грам",
    picture: "czezar.webp",
  },
];
