export const ingredientsData = [
  {
    id: 1,
    name: "Сир Дор-Блю",
    img: "syr-dor-blyu.webp",
    weight: 50,
    price: 64,
    category: "cheese",
  },
  {
    id: 2,
    name: "Сир Королівський",
    img: "krolivskyj-syr.webp",
    weight: 50,
    price: 44,
    category: "cheese",
  },
  {
    id: 3,
    name: "Сир Моцарелла",
    img: "moczarella.webp",
    weight: 50,
    price: 39,
    category: "cheese",
  },
  {
    id: 4,
    name: "Сир Пармезан",
    img: "syr-parmyzan.webp",
    weight: 48,
    price: 84,
    category: "cheese",
  },
  {
    id: 5,
    name: "Сир Фета",
    img: "feta.webp",
    weight: 50,
    price: 28,
    category: "cheese",
  },
  {
    id: 6,
    name: "Бекон",
    img: "bekon.webp",
    weight: 50,
    price: 39,
    category: "meat",
  },
  {
    id: 7,
    name: "Мисливські Ковбаски",
    img: "myslyvski-kovbasky.webp",
    weight: 50,
    price: 32,
    category: "meat",
  },
  {
    id: 8,
    name: "Папероні",
    img: "paperoni.webp",
    weight: 50,
    price: 47,
    category: "meat",
  },
  {
    id: 9,
    name: "Салямі",
    img: "salyami.webp",
    weight: 50,
    price: 34,
    category: "meat",
  },
  {
    id: 10,
    name: "Шинка",
    img: "shynka.webp",
    weight: 50,
    price: 28,
    category: "meat",
  },
  {
    id: 11,
    name: "Печериці",
    img: "gryby.webp",
    weight: 50,
    price: 24,
    category: "vegetables",
  },
  {
    id: 12,
    name: "Кукурудза",
    img: "kukurudza.webp",
    weight: 50,
    price: 19,
    category: "vegetables",
  },
  {
    id: 13,
    name: "Маслини",
    img: "olyvky.png",
    weight: 50,
    price: 36,
    category: "vegetables",
  },
  {
    id: 14,
    name: "Маренований огірок",
    img: "marynovani-ogirky.png",
    weight: 50,
    price: 18,
    category: "vegetables",
  },
  {
    id: 15,
    name: "Руккола",
    img: "rukola.png",
    weight: 50,
    price: 14,
    category: "vegetables",
  },
  {
    id: 16,
    name: "Цибуля",
    img: "czybulya.webp",
    weight: 50,
    price: 15,
    category: "vegetables",
  },
  {
    id: 17,
    name: "Перець чилі",
    img: "chili.webp",
    weight: 30,
    price: 8,
    category: "vegetables",
  },
  {
    id: 18,
    name: "Часник",
    img: "chasnyk.webp",
    weight: 25,
    price: 12,
    category: "vegetables",
  },
  {
    id: 19,
    name: "Помідори чері",
    img: "tomaty.png",
    weight: 50,
    price: 26,
    category: "vegetables",
  },
  {
    id: 20,
    name: "Помідори",
    img: "pomidor.png",
    weight: 50,
    price: 28,
    category: "vegetables",
  },
  {
    id: 21,
    name: "Ананас",
    img: "ananas.webp",
    weight: 50,
    price: 32,
    category: "fruits",
  },
  {
    id: 22,
    name: "Лемон",
    img: "lymon.png",
    weight: 40,
    price: 15,
    category: "fruits",
  },
  {
    id: 23,
    name: "Крабові Палички",
    img: "krabovi-palochky.webp",
    weight: 50,
    price: 49,
    category: "fish",
  },
  {
    id: 24,
    name: "Лосось",
    img: "losos.webp",
    weight: 50,
    price: 92,
    category: "fish",
  },
  {
    id: 25,
    name: "Вершковий соус",
    img: "vershkowa.png",
    weight: 50,
    price: 16,
    category: "base",
  },
  {
    id: 26,
    name: "Томатний соус",
    img: "tomatna.png",
    weight: 50,
    price: 16,
    category: "base",
  },
  {
    id: 27,
    name: "Часниковий соус",
    img: "chasnikova.png",
    weight: 50,
    price: 16,
    category: "base",
  },
  {
    id: 28,
    name: "Гострий соус",
    img: "ostra.png",
    weight: 50,
    price: 16,
    category: "base",
  },
  {
    id: 29,
    name: "Цезар соус",
    img: "cesar.png",
    weight: 50,
    price: 16,
    category: "base",
  },
];
