export const ingredientsData = [
  {
    id: 1,
    name: "Сир Дор-Блю",
    img: "cheese.png",
    weight: 50,
    price: 64,
    category: "cheese",
  },
  {
    id: 2,
    name: "Сир Королівський",
    img: "ham.png",
    weight: 50,
    price: 44,
    category: "cheese",
  },
  {
    id: 3,
    name: "Сир Моцарелла",
    img: "tomato.png",
    weight: 50,
    price: 39,
    category: "cheese",
  },
  {
    id: 4,
    name: "Сир Пармезан",
    img: "corn.png",
    weight: 48,
    price: 84,
    category: "cheese",
  },
  {
    id: 5,
    name: "Сир Фета",
    img: "mushroom.png",
    weight: 50,
    price: 28,
    category: "cheese",
  },
  {
    id: 6,
    name: "Бекон",
    img: "cheese.png",
    weight: 50,
    price: 39,
    category: "meat",
  },
  {
    id: 7,
    name: "Мисливські Ковбаски",
    img: "ham.png",
    weight: 50,
    price: 32,
    category: "meat",
  },
  {
    id: 8,
    name: "Папероні",
    img: "tomato.png",
    weight: 50,
    price: 47,
    category: "meat",
  },
  {
    id: 9,
    name: "Салямі",
    img: "corn.png",
    weight: 50,
    price: 34,
    category: "meat",
  },
  {
    id: 10,
    name: "Шинка",
    img: "mushroom.png",
    weight: 50,
    price: 28,
    category: "meat",
  },
  {
    id: 11,
    name: "Печериці",
    img: "cheese.png",
    weight: 50,
    price: 24,
    category: "meat",
  },
  {
    id: 12,
    name: "Кукурудза",
    img: "ham.png",
    weight: 50,
    price: 19,
    category: "vegetables",
  },
  {
    id: 13,
    name: "Маслини",
    img: "tomato.png",
    weight: 50,
    price: 36,
    category: "vegetables",
  },
  {
    id: 14,
    name: "Маренований огірок",
    img: "corn.png",
    weight: 50,
    price: 18,
    category: "vegetables",
  },
  {
    id: 15,
    name: "Руккола",
    img: "mushroom.png",
    weight: 50,
    price: 14,
    category: "vegetables",
  },
  {
    id: 16,
    name: "Цибуля",
    img: "cheese.png",
    weight: 50,
    price: 15,
    category: "vegetables",
  },
  {
    id: 17,
    name: "Перець чилі",
    img: "ham.png",
    weight: 30,
    price: 8,
    category: "vegetables",
  },
  {
    id: 18,
    name: "Часник",
    img: "tomato.png",
    weight: 25,
    price: 12,
    category: "vegetables",
  },
  {
    id: 19,
    name: "Помідори чері",
    img: "corn.png",
    weight: 50,
    price: 26,
    category: "vegetables",
  },
  {
    id: 20,
    name: "Помідори",
    img: "mushroom.png",
    weight: 50,
    price: 28,
    category: "vegetables",
  },
  {
    id: 21,
    name: "Ананас",
    img: "cheese.png",
    weight: 50,
    price: 32,
    category: "fruits",
  },
  {
    id: 22,
    name: "Лемон",
    img: "ham.png",
    weight: 40,
    price: 15,
    category: "fruits",
  },
  {
    id: 23,
    name: "Крабові Палички",
    img: "tomato.png",
    weight: 50,
    price: 49,
    category: "fish",
  },
  {
    id: 24,
    name: "Лосось",
    img: "corn.png",
    weight: 50,
    price: 92,
    category: "fish",
  },
  {
    id: 25,
    name: "Вершкова основа",
    img: "mushroom.png",
    weight: 50,
    price: 16,
    category: "base",
  },
  {
    id: 26,
    name: "Томатна основа",
    img: "cheese.png",
    weight: 50,
    price: 16,
    category: "base",
  },
  {
    id: 27,
    name: "Часникова основа",
    img: "ham.png",
    weight: 50,
    price: 16,
    category: "base",
  },
];
