export const itemsData = [
  {
    id: 1,
    title: "Каріна",
    ingredients: "вершки, сир, шинка, курка, печериці, кукурудза",
    img: "karina.png",
    picture: "karina.png",
    weight: "600 грам - ",
    price: 265,
  },
  {
    id: 2,
    title: "Гавайська",
    ingredients: "курка, вершки, ананас, сир",
    img: "gavai.png",
    picture: "gavai.png",
    weight: "560 грам - ",
    price: 263,
  },
  {
    id: 3,
    title: "Бланкос",
    ingredients:
      "орегано, томатний соус, сир, салямі, шинка, зелень, вершки після печі",
    img: "blankos.png",
    picture: "blankos.png",
    weight: "600 грам - ",
    price: 267,
  },
  {
    id: 4,
    title: "П'ять сирів",
    ingredients: "вершки, моцарела, дорблю, пармезан, чеддер, фета",
    img: "5cheese.png",
    picture: "5cheese.png",
    weight: "575 грам - ",
    price: 266,
  },
  {
    id: 5,
    title: "Войт",
    ingredients: "вершки, сир, салямі, шинка, курка, кукурудза, помідори чері",
    img: "voit.png",
    picture: "voit.png",
    weight: "710 грам - ",
    price: 276,
  },
  {
    id: 6,
    title: "Маргарита",
    ingredients: "орегано, томатний соус, сир",
    img: "margarita.png",
    picture: "margarita.png",
    weight: "440 грам - ",
    price: 240,
  },
  {
    id: 7,
    title: "Курка BBQ",
    ingredients:
      "орегано, томатний соус, сир, печериці, курка, перець, соус барбекю",
    img: "chickenBBQ.png",
    picture: "chickenBBQ.png",
    weight: "600 грам - ",
    price: 264,
  },
  {
    id: 8,
    title: "Салмон",
    ingredients:
      "вершково-шпинатний соус, сир, лосось, маслини, крем-сир, рукола",
    img: "salmon.png",
    picture: "salmon.png",
    weight: "650 грам - ",
    price: 347,
  },
  {
    id: 9,
    title: "Опера",
    ingredients:
      "орегано, томатний соус, сир, тунець, цибуля, помідори чері, рукола",
    img: "opera.png",
    picture: "opera.png",
    weight: "590 грам - ",
    price: 290,
  },
  {
    id: 10,
    title: "Везувіо",
    ingredients: "орегано, томатний соус, сир, шинка",
    img: "vesuvio.png",
    picture: "vesuvio.png",
    weight: "500 грам - ",
    price: 244,
  },
  {
    id: 11,
    title: "Броколі",
    ingredients: "орегано, томатний соус, сир, салямі, броколі",
    img: "brokoly.png",
    picture: "brokoly.png",
    weight: "630 грам - ",
    price: 263,
  },
  {
    id: 12,
    title: "Констуктор піци",
    ingredients: "вибирай начинку сам",
    img: "konstruktor.png",
    picture: "konstruktor.png",
    weight: "від 315 грам - ",
    price: 150,
  },
];
